
var CatalogDisplayManager=imports("freequery.catalogdisplay.CatalogDisplayManager")
var CatalogDisplayAction=function(treeSlot,toolbarSlot,viewSlot,leftPane,splitter,tabSlot){this.text="个人目录";this.treeSlot=treeSlot;this.toolbarSlot=toolbarSlot;this.viewSlot=viewSlot;this.leftPane=leftPane;this.splitter=splitter;this.tabSlot=tabSlot;this.status="hidden";};lang.extend(CatalogDisplayAction,"bof.baseajax.common.AbstractAction");CatalogDisplayAction.prototype.open=function(arg){if(!this.catalogDisplayManager){this.catalogDisplayManager=new CatalogDisplayManager(this.treeSlot,this.viewSlot,this);}
if(this.status=="hidden"){this.toolbarSlot.style.display="none";this.catalogDisplayManager.show();this.status="shown";this.openRelatePage();}
return true;};CatalogDisplayAction.prototype.close=function(arg){if(this.catalogDisplayManager&&this.status=="shown"){this.toolbarSlot.style.display="";this.catalogDisplayManager.showTreeView();this.catalogDisplayManager.hide();this.status="hidden";}
return true;};CatalogDisplayAction.prototype.destroy=function(){CatalogDisplayAction.superclass.destroy.call(this);if(this.catalogDisplayManager){this.catalogDisplayManager.destroy();this.catalogDisplayManager=null;}};CatalogDisplayAction.prototype.getViewObject=function(){return this.catalogDisplayManager;};CatalogDisplayAction.prototype.openRelatePage=function(){var url=null;if(this.parentAction&&this.parentAction.config&&this.parentAction.config.actions){var configActions=this.parentAction.config.actions;for(var i=0,len=configActions.length;i<len;i++){var currAction=configActions[i];if(currAction.id==this.id){url=currAction.relatePage;if(!url&&currAction.type&&currAction.type!='DEFAULT_TREENODE'){url='openresource.jsp?isBrowse=true&refresh=true&resid='+this.id;this.catalogDisplayManager.hideTreeView();}
break;}}}
if(url){if(/openresource.jsp\?/.test(url)){url+='&showPath=false';}
var command=this.urlCommand;if(!command){var URLLinkCommand=jsloader.resolve('freequery.sysresource.URLLinkCommand');command=this.urlCommand=new URLLinkCommand();}
var tab=this.catalogDisplayManager.createTab(this.id,this.text);if(tab){command.parentObj=document.getElementById('rigthContent')||document.body;var openResult=command.openLinkInCurrentWindow(url);this.catalogDisplayManager.setCommand(tab,command);if(openResult===false){tab.doClose();}else{if(command.frameView){command.frameView.hideLocationBar();}}}}};