
var TreeNode=jsloader.resolve("freequery.tree.TreeNode");var CatalogTreeNode=jsloader.resolve("freequery.tree.CatalogTreeNode");var Level1CatalogTreeNode=function(text,level,mayHasChild,parent,id){Level1CatalogTreeNode.superclass.constructor.call(this,text,level,mayHasChild,parent,id);this.expander.style.display="none";this.icon.style.display="none";if(domutils.isIE()){var text=this.textSpan.innerText;this.textSpan.innerText="";this.hiddenLink=document.createElement("A");this.hiddenLink.style.textDecoration="none";this.hiddenLink.href="#";this.hiddenLink.innerHTML=text;this.textSpan.appendChild(this.hiddenLink);this.addListener(this.hiddenLink,"click",this.handleHiddeLinkClick,this);this.fakeSpan=document.createElement("SPAN");this.textSpan.appendChild(this.fakeSpan);this.fakeSpan.style.visibility="hidden";this.fakeSpan.appendChild(document.createTextNode(' '));}else{this.hiddenLink.style.color="";this.hiddenLink.style.cursor="";}
domutils.removeClassName(this.textSpan,"tree_textSpan");domutils.addClassName(this.textSpan,"flat-level1-tree-textSpan");domutils.addClassName(this.hiddenLink,"flat-level1-tree-link");domutils.addClassName(this.hiddenLink,"close");this.addListener(this.hiddenLink,"mouseover",this.doOnLevel1TreeNodeMouseOver,this);this.addListener(this.hiddenLink,"mouseout",this.doOnLevel1TreeNodeMouseOut,this);};lang.extend(Level1CatalogTreeNode,CatalogTreeNode);Level1CatalogTreeNode.prototype.setIcon=function(icon){if(icon==null){this.icon.style.display="none";}
this.icon.src=icon;}
Level1CatalogTreeNode.prototype.setText=function(text){var child=this.textSpan.firstChild;while(child!=null){if(child.nodeType==3){domutils.destroyNode(child);}
child=child.nextSibling;}
if(!this.disableShortTip&&util.getCharLength(text)>TreeNode.NODE_NAME_MAX_LENGTH){this.longText=text;text=util.getShortString(text,TreeNode.NODE_NAME_MAX_LENGTH,"...");}else{this.longText=undefined;}
this.hiddenLink.innerHTML=text;this.text=text;var iconSpan=document.createElement("SPAN");iconSpan.className="flat-icon";if(this._customImage!=null&&this._customImage!=""){this.setIcon("img/catalogtree/"+this._customImage);iconSpan.style.background="url("+"img/catalogtree/"+this._customImage+") no-repeat center";this.icon.onerror=function(ev){iconSpan.style.background="url(img/catalogtree/"+this.catalog.type+".png) no-repeat center";}}else if(this.catalog.type!="DEFAULT_TREENODE"){iconSpan.style.background="url(img/catalogtree/"+this.catalog.type+".png) no-repeat center";}
this.hiddenLink.appendChild(iconSpan);if(!this._hasChild){domutils.removeClassName(this.hiddenLink,"close");}}
Level1CatalogTreeNode.prototype.isHiddenNode=function(catalog){var _showOnPC=catalog.showOnPC;if(catalog.extended==""||(catalog.extended&&catalog.extended.indexOf("showOnPC")==-1)){_showOnPC=true;}
if(_showOnPC!=undefined&&!_showOnPC){return true;}
return Level1CatalogTreeNode.superclass.isHiddenNode.call(this,catalog);}
Level1CatalogTreeNode.prototype.doOnMouseDown=function(e,target){var button=domutils.isIE()?e.button:e.buttons;var isRightButton=domutils.isRightButton(button);this.tree.isRightButton=isRightButton;if(this.tree.currentLevel1Node&&!(this.tree.currentLevel1Node==this)){var currentLevel1Node=this.tree.currentLevel1Node;if(currentLevel1Node.childSpan){currentLevel1Node.childSpan.style.display="none";}
if(this._hasChild&&!isRightButton){domutils.removeClassName(currentLevel1Node.hiddenLink,"open");domutils.addClassName(currentLevel1Node.hiddenLink,"close");}}
if(this._hasChild){this.doOnExpanderMouseDown(e);this.lastClientX=e.clientX;this.lastClientY=e.clientY;this.addListener(document,"mousemove",this.doOnMouseMove,this);this.addListener(document,"mouseup",this.doOnMouseUp,this);if(this.hiddenLink&&!isRightButton){if(domutils.hasClassName(this.hiddenLink,"open")==true){domutils.removeClassName(this.hiddenLink,"open");domutils.addClassName(this.hiddenLink,"close");}else if(domutils.hasClassName(this.hiddenLink,"close")==true){domutils.removeClassName(this.hiddenLink,"close");domutils.addClassName(this.hiddenLink,"open");}}
this.tree.currentLevel1Node=this;}else{if(button!==4&&!(e.ctrlKey&&button===1)){if(!isRightButton){this.tree.selectNodeWithoutFire(this,false);this.tree.doCmd("OPEN");}}else{if(!this._hasChild){var url="openresource.jsp?resid="+this._id;url+="&refresh=true&browserType="+domutils.getBrowserType();window.open(url);}}}
if(isRightButton){this.doOnTextSpanMouseDown(e);}
if(domutils.isFirefox()){domutils.stopEvent(e);}};Level1CatalogTreeNode.prototype.doOnLevel1TreeNodeMouseOver=function(e){domutils.removeClassName(this.hiddenLink,"flat-level1-tree-link");domutils.addClassName(this.hiddenLink,"flat-level1-tree-link_hover");};Level1CatalogTreeNode.prototype.doOnLevel1TreeNodeMouseOut=function(e){domutils.removeClassName(this.hiddenLink,"flat-level1-tree-link_hover");domutils.addClassName(this.hiddenLink,"flat-level1-tree-link");};Level1CatalogTreeNode.prototype.destroy=function(){Level1CatalogTreeNode.superclass.destroy.call(this);this.removeListener(this.hiddenLink,"mouseover",this.doOnLevel1TreeNodeMouseOver);this.removeListener(this.hiddenLink,"mouseout",this.doOnLevel1TreeNodeMouseOut);}