
var Module=jsloader.resolve("freequery.widget.Module");var CustomEvent=jsloader.resolve("freequery.lang.CustomEvent");var util=jsloader.resolve("freequery.common.util");var TabPages=jsloader.resolve("freequery.control.TabPages");var LimitTabPages=function(container,options){this.container=container;if("string"==typeof options){if(options=="MAIN"||options=="CMNT"||options=="CMNB"||options=="FLAT"){options=TabPages.getOptions(options);}}
this.options=options||{};this.classNames=this.options.classNames||{};if(this.options.tabPosition)
this.tabPosition=this.options.tabPosition.toUpperCase();else
this.tabPosition="TOP";this.tabPanel=domutils.createElement("div");if(this.classNames.tabPanel)
this.tabPanel.className=this.classNames.tabPanel;this.container.appendChild(this.tabPanel);this.tabPanelHeader=domutils.createElement("div");if(this.classNames.tabPanelHeader)
this.tabPanelHeader.className=this.classNames.tabPanelHeader;this.tabPanel.appendChild(this.tabPanelHeader);if(this.options.tabPanelHeaderWidth)
this.tabPanelHeader.style.width=this.options.tabPanelHeaderWidth;if(this.options.tabPanelHeaderHeight)
this.tabPanelHeader.style.height=this.options.tabPanelHeaderHeight;this.tabPanelBodyWrap=domutils.createElement("div");if(this.classNames.tabPanelBodyWrap)
this.tabPanelBodyWrap.className=this.classNames.tabPanelBodyWrap;if("BOTTOM"==this.tabPosition)
this.tabPanel.insertBefore(this.tabPanelBodyWrap,this.tabPanelHeader);else
this.tabPanel.appendChild(this.tabPanelBodyWrap);if(this.options.tabPanelBodyWidth){this.tabPanelBodyWrap.style.width=this.options.tabPanelBodyWidth;this.tabPanelHeader.style.width=this.options.tabPanelBodyWidth;}
if(this.options.tabPanelBodyHeight)
this.tabPanelBodyWrap.style.height=this.options.tabPanelBodyHeight;this.tabPanelBodyWrap.oldDisplay=this.tabPanelBodyWrap.style.display;this.tabPanelBodyWrap.style.display="none";this.tabStripSpacer=domutils.createElement("div");if(this.classNames.tabStripSpacer)
this.tabStripSpacer.className=this.classNames.tabStripSpacer;this.tabPanelHeader.appendChild(this.tabStripSpacer);this.tabStripWrap=domutils.createElement("div");if(domutils.isChrome()||domutils.isFirefox()||domutils.isSafari()||domutils.isIE()&&domutils.getBrowserVersion()>9&&document.documentMode&&document.documentMode>9){this.tabStripWrap.style.width="inherit";}
if(this.classNames.tabStripWrap)
this.tabStripWrap.className=this.classNames.tabStripWrap;this.tabPanelHeader.appendChild(this.tabStripWrap);this.tabStrip=domutils.createElement("div");if(this.classNames.tabStrip)
this.tabStrip.className=this.classNames.tabStrip;this.tabStripWrap.appendChild(this.tabStrip);this.tabPanelBody=domutils.createElement("div");if(this.classNames.tabPanelBody)
this.tabPanelBody.className=this.classNames.tabPanelBody;this.tabPanelBodyWrap.appendChild(this.tabPanelBody);this.tabObjs=new Array();this.hiddenTabObjs=new Array();this.tempTabWidth=0;this.stepsMoveToLeft=0;this.onTabClick=new CustomEvent("onTabClick",this);this.onTabClick.terminateOnFalse=true;this.onTabActive=new CustomEvent("onTabActive",this);this.onTabClose=new CustomEvent("onTabClose",this);this.limitDocElement=document.getElementById('mainTable')||document.body;}
lang.extend(LimitTabPages,TabPages);LimitTabPages.prototype.appendTab=function(tabTitle,imgSrc,closable,tabOnly,contentElement,tabId){var contentEl=null;if(!tabOnly){contentEl=contentElement;if(contentEl==null||'object'!=typeof contentEl||contentEl.nodeType!=1){contentEl=domutils.createElement("div");contentEl.dynamic=true;if(this.classNames.tabBody){contentEl.className=this.classNames.tabBody;}else{contentEl.style.width="100%";contentEl.style.height="100%";}
if(this.tabPanelBodyWrap.style.display=="none"){this.tabPanelBodyWrap.style.display=this.tabPanelBodyWrap.oldDisplay;}
this.tabPanelBody.appendChild(contentEl);}else{if(this.classNames.tabBody){contentEl.className=this.classNames.tabBody;}}
contentEl.oldDisplay=contentEl.style.display;contentEl.style.display="none";}
var tab=new Tab(this.tabStrip,tabTitle,imgSrc,closable,contentEl,tabId,this.options.tabOptions,this);tab.onClick.subscribe(this.doTabClick,this);tab.onActive.subscribe(this.doTabActive,this);tab.onClose.subscribe(this.doTabClose,this);tab.onVisibleChanged.subscribe(this.doTabVisibleChanged,this);tab.onCaptionChanged.subscribe(this.doTabCaptionChanged,this);this.tabObjs.push(tab);if(!this.activeTab){this.tabObjs[0].setActive(true);}
tab.visible=false;tab.setVisibleOnly(false);this.hiddenTabObjs.push(tab);this.autoFitResize();return tab;}
LimitTabPages.prototype.autoFitResize=function(){if(this.container.clientWidth==0){return;}
if(this.getSpareWidth()>0){if(this.hiddenTabObjs&&this.hiddenTabObjs.length>0){this.reshowHiddenTabs();}}else{this.hideTabs();}
if(typeof this.btnMore!='undefined'){var show=this.hiddenTabObjs.length>0?true:this.getSpareWidth()<0?true:false;this.btnMore.style.display=show?"":"none";this.btnMore.innerHTML=this.hiddenTabObjs.length;}}
LimitTabPages.prototype.reshowHiddenTabs=function(){var i=0;while(i<this.hiddenTabObjs.length){if(this.getSpareWidth()>this.hiddenTabObjs[i].width){this.hiddenTabObjs[i].setVisibleOnly(true);this.hiddenTabObjs[i].visible=true;this.hiddenTabObjs.splice(i,1);}else{i++;}}}
LimitTabPages.prototype.hideTabs=function(){var spareWidth=this.getSpareWidth();while(spareWidth<0){this.hideFirstVisibleTab();spareWidth=this.getSpareWidth();}}
LimitTabPages.prototype.updateTabOrder=function(orders){this.deleteMoreBtn();this.tabObjs=LimitTabPages.superclass.updateTabOrder.call(this,orders);this.initMoreBtn();return this.tabObjs;}
LimitTabPages.prototype.initMoreBtn=function(){if(typeof this.moreBtnDiv=='undefined'){this.moreBtnDiv=domutils.createElement("div");if(this.classNames.tabScrollLeft){this.moreBtnDiv.className=this.classNames.tabHeader;}
this.tabStrip.appendChild(this.moreBtnDiv);this.btnMore=domutils.createElement("span");this.btnMore.className="btn-more-flat";this.moreBtnDiv.appendChild(this.btnMore);this.btnMore.innerHTML=this.hiddenTabObjs.length;this.addListener(this.btnMore,"click",this.onBtnMoreClick,this);this.addListener(this.btnMore,"mouseover",this.onBtnMoreMouseOver,this);this.addListener(this.btnMore,"mouseout",this.onBtnMoreMouseOut,this);this.morePanelBody=domutils.createElement("div");this.morePanelBody.className='morePanel-flat';this.container.parentNode.appendChild(this.morePanelBody);this.morePanelBody.style.display="none";this.addListener(this.morePanelBody,"click",this.openTab,this);this.addListener(window,"resize",this.doWindowResize,this);}}
LimitTabPages.prototype.onBtnMoreClick=function(e){if(this.morePanelBody.style.display=="none"){this.setMorePanelVisible(true);}else{this.setMorePanelVisible(false);}
domutils.stopEvent(e);}
LimitTabPages.prototype.onBtnMoreMouseOver=function(e){var e=e||event;var target=e.target||e.srcElement;if(target){domutils.replaceClassName(target,"btn-more-flat-select","btn-more-flat");}}
LimitTabPages.prototype.onBtnMoreMouseOut=function(e){var e=e||event;var target=e.target||e.srcElement;if(target){domutils.replaceClassName(target,"btn-more-flat","btn-more-flat-select");}}
LimitTabPages.prototype.setMorePanelVisible=function(visible){this.morePanelBody.style.display=(!!visible)?"":"none";if(!visible){this.bindDocMouseDown(false);return;}else{this.bindDocMouseDown(true);}
var child=this.morePanelBody.firstChild;while(child!=null){this.removeListener(child,"mouseover",this.handlePanelItemMouseOver,this);this.removeListener(child,"mouseout",this.handlePanelItemMouseOut,this);domutils.destroyNode(child,true);child=this.morePanelBody.firstChild;}
for(var i=0,len=this.hiddenTabObjs.length;i<len;i++){var tab=this.hiddenTabObjs[i];var div=domutils.createElement("div");div.className='morePanelItem-flat-hidden';div.innerHTML=tab.title;div.tabObj=tab;div.tabIndex=i;this.addListener(div,"mouseover",this.handlePanelItemMouseOver,this);this.addListener(div,"mouseout",this.handlePanelItemMouseOut,this);this.morePanelBody.appendChild(div);}
for(var i=0,len=this.tabObjs.length;i<len;i++){var tab=this.tabObjs[i];if(tab.getVisible()){var div=domutils.createElement("div");div.className='morePanelItem-flat';div.innerHTML=tab.title;div.tabObj=tab;div.tabIndex=i;this.addListener(div,"mouseover",this.handlePanelItemMouseOver,this);this.addListener(div,"mouseout",this.handlePanelItemMouseOut,this);this.morePanelBody.appendChild(div);}}
if(this.tabObjs.length>22){this.morePanelBody.style.overflowX="hidden";this.morePanelBody.style.overflowY="auto";this.morePanelBody.style.height="500px";}}
LimitTabPages.prototype.handlePanelItemMouseOver=function(e){var e=e||event;var target=e.target||e.srcElement;if(target){if(domutils.hasClassName(target,"morePanelItem-flat")==true){domutils.replaceClassName(target,"morePanelItem-flat-select","morePanelItem-flat");}
if(domutils.hasClassName(target,"morePanelItem-flat-hidden")==true){domutils.replaceClassName(target,"morePanelItem-flat-hidden-select","morePanelItem-flat-hidden");}}}
LimitTabPages.prototype.handlePanelItemMouseOut=function(e){var e=e||event;var target=e.target||e.srcElement;if(target){if(domutils.hasClassName(target,"morePanelItem-flat-select")==true){domutils.replaceClassName(target,"morePanelItem-flat","morePanelItem-flat-select");}
if(domutils.hasClassName(target,"morePanelItem-flat-hidden-select")==true){domutils.replaceClassName(target,"morePanelItem-flat-hidden","morePanelItem-flat-hidden-select");}}}
LimitTabPages.prototype.destroy=function(){if(typeof this.hiddenTabObjs!='undefined'){this.hiddenTabObjs=null;delete this.hiddenTabObjs;}
if(typeof this.tempTabWidth!='undefined'){this.tempTabWidth=null;delete this.tempTabWidth;}
if(typeof this.btnMore!='undefined'){this.removeListener(window,"resize",this.doWindowResize);this.removeListener(this.btnMore,"click",this.onBtnMoreClick);this.removeListener(this.btnMore,"mouseover",this.onBtnMoreMouseOver);this.removeListener(this.btnMore,"mouseout",this.onBtnMoreMouseOut);this.btnMore=null;delete this.btnMore;}
if(typeof this.morePanelBody!='undefined'){this.removeListener(this.morePanelBody,"click",this.openTab);this.morePanelBody=null;delete this.morePanelBody;}
if(typeof this.moreBtnDiv!='undefined'){this.moreBtnDiv=null;delete this.moreBtnDiv;}
this.bindDocMouseDown(false);LimitTabPages.superclass.destroy.call(this);};LimitTabPages.prototype.bindDocMouseDown=function(isAddListener){if(isAddListener){if(!this._isBoundDocMouseDown){this.addListener(this.limitDocElement,"mousedown",this.doLimitDocMouseDown,this);this._isBoundDocMouseDown=true;}}else{if(this._isBoundDocMouseDown){this.removeListener(this.limitDocElement,"mousedown",this.doLimitDocMouseDown,this);this._isBoundDocMouseDown=null;delete this._isBoundDocMouseDown;}}};LimitTabPages.prototype.doLimitDocMouseDown=function(e){var target=e.target,t=this;if(!t.elementInPanel(target,t.morePanelBody)){t.setMorePanelVisible(false);}};LimitTabPages.prototype.elementInPanel=function(el,panel){if(panel){while(el!=null){if(el==panel){return true;}else{el=el.parentNode;}}}
return false;};LimitTabPages.prototype.deleteMoreBtn=function(){if(typeof this.moreBtnDiv!='undefined'){this.moreBtnDiv.removeChild(this.btnMore);this.tabStrip.removeChild(this.moreBtnDiv);this.container.parentNode.removeChild(this.morePanelBody);delete this.moreBtnDiv;}}
LimitTabPages.prototype.openTab=function(e){var e=e||event;var target=e.target||e.srcElement;if(!target){return;}
var tab=target.tabObj;if(tab){this.reshowTab(tab);this.setMorePanelVisible(false);tab.doClick();}}
LimitTabPages.prototype.reshowTab=function(tab){if(!tab){this.autoFitResize();return;}
var spareWidth=this.getSpareWidth();while(spareWidth<tab.width&&this.hiddenTabObjs.length<this.tabObjs.length-1){this.hideFirstVisibleTab();spareWidth=this.getSpareWidth();}
tab.setVisibleOnly(true);tab.visible=true;for(var i=0,len=this.hiddenTabObjs.length;i<len;i++){if(this.hiddenTabObjs[i].id==tab.id){this.hiddenTabObjs.splice(i,1)[0];break;}}
this.autoFitResize();}
LimitTabPages.prototype.getSpareWidth=function(){var tempTabWidth=0;for(var i=0;i<this.tabObjs.length;i++){if(this.tabObjs[i].visible){tempTabWidth+=this.tabObjs[i].width;}}
return(this.container.clientWidth-tempTabWidth-35);}
LimitTabPages.prototype.hideFirstVisibleTab=function(){for(var i=0;i<this.tabObjs.length;i++){var obj=this.tabObjs[i];if(obj.active){continue;}
obj.setVisibleOnly(false);obj.visible=false;var isExist=false;for(var j=0;j<this.hiddenTabObjs.length;j++){if(this.hiddenTabObjs[j].id==obj.id){isExist=true;break;}}
if(!isExist){obj.visible=false;this.hiddenTabObjs.push(obj);break;}}}
var Tab=function(container,caption,imgSrc,closable,contentEl,tabId,options,tabPages){this.container=container;this.title=caption;this.imgSrc=imgSrc;this.contentEl=contentEl;this.options=options||{};this.tabPages=tabPages;this.classNames=this.options.classNames||{};this.closable=!!closable&&(this.options.closeImgSrc!=undefined);this.active=false;this.isMouseOver=false;this.visible=true;this.parent=domutils.createElement("div");if(this.tabPages&&this.tabPages.classNames.tabHeader)
this.parent.className=this.tabPages.classNames.tabHeader;this.parent.oldDisplay=this.parent.style.display;this.container.appendChild(this.parent);if(this.parent.offsetWidth==this.container.offsetWidth){this.parent.style.position="relative";this.parent.style.float="left";}
this.id=tabId||this.parent.id||domutils.generateId();this.spanL=domutils.createElement("span");this.parent.appendChild(this.spanL);this.spanM=domutils.createElement("span");this.parent.appendChild(this.spanM);if(this.imgSrc){this.icon=domutils.createElement("img");this.icon.src=this.imgSrc;this.icon.align="absmiddle";this.spanM.appendChild(this.icon);this.spanSpaceH=domutils.createElement("span");this.spanSpaceH.style.width="6px";this.spanM.appendChild(this.spanSpaceH);}
this.spanText=domutils.createElement("span");this.spanText.innerHTML=this.title;this.spanM.appendChild(this.spanText);if(this.closable){this.spanSpaceT=domutils.createElement("span");this.spanSpaceT.style.width="18px";this.spanM.appendChild(this.spanSpaceT);this.btnClose=domutils.createElement("img");this.btnClose.src=this.options.closeImgSrc;this.btnClose.align="absmiddle";this.btnClose.title="关闭";this.spanM.appendChild(this.btnClose);this.addListener(this.btnClose,"click",this.doClose,this);if(this.options.closeImgOnSrc){this.addListener(this.btnClose,"mouseover",this.doBtnCloseMouseOver,this);this.addListener(this.btnClose,"mouseout",this.doBtnCloseMouseOut,this);}}
this.spanR=domutils.createElement("span");this.parent.appendChild(this.spanR);this.onClick=new CustomEvent("onClick",this);this.onClick.terminateOnFalse=true;this.onActive=new CustomEvent("onActive",this);this.onClose=new CustomEvent("onClose",this);this.onVisibleChanged=new CustomEvent("onVisibleChanged",this);this.onCaptionChanged=new CustomEvent("onCaptionChanged",this);this.addListener(this.parent,"click",this.doClick,this);this.addListener(this.parent,"mouseover",this.doMouseOver,this);this.addListener(this.parent,"mouseout",this.doMouseOut,this);this.updateClassName();this.width=this.getElement().offsetWidth;}
lang.extend(Tab,TabPages.Tab);Tab.prototype.setVisibleOnly=function(value){if(!this.parent){return;}
var tmpDisplay=this.parent.style.display;this.parent.style.display=(!!value)?this.parent.oldDisplay:"none";}